import { appNameCode } from '.';

const APP_NAME_CODES = {
  HYBRID_RESEARCH_CENTER: 'hrc',
  EMIRATES_RESEARCH_CENTER: 'erc',
  DIGITAL_SKY_SERVICES: 'dss',
  BRAIN_BENCH: 'bb',
};

const ALL_CURRENCIES_OBJ = {
  USD: {
    name: 'America (United States) Dollars - USD',
    code: 'USD',
    symbol: '$',
  },
  AFN: { name: 'Afghanistan Afghanis - AFN', code: 'AFN', symbol: '؋' },
  ALL: { name: 'Albania Leke - ALL', code: 'ALL', symbol: 'Lek' },
  DZD: { name: 'Algeria Dinars - DZD', code: 'DZD', symbol: 'د.ج' },
  ARS: { name: 'Argentina Pesos - ARS', code: 'ARS', symbol: '$' },
  AUD: { name: 'Australia Dollars - AUD', code: 'AUD', symbol: '$' },
  ATS: { name: 'Austria Schillings - ATS', code: 'ATS', symbol: 'S' },
  BSD: { name: 'Bahamas Dollars - BSD', code: 'BSD', symbol: '$' },
  BHD: { name: 'Bahrain Dinars - BHD', code: 'BHD', symbol: '.د.ب' },
  BDT: { name: 'Bangladesh Taka - BDT', code: 'BDT', symbol: '৳' },
  BBD: { name: 'Barbados Dollars - BBD', code: 'BBD', symbol: '$' },
  BEF: { name: 'Belgium Francs - BEF', code: 'BEF', symbol: 'fr.' },
  BMD: { name: 'Bermuda Dollars - BMD', code: 'BMD', symbol: '$' },
  BRL: { name: 'Brazil Reais - BRL', code: 'BRL', symbol: 'R$' },
  BGN: { name: 'Bulgaria Leva - BGN', code: 'BGN', symbol: 'лв' },
  CAD: { name: 'Canada Dollars - CAD', code: 'CAD', symbol: '$' },
  XOF: { name: 'CFA BCEAO Francs - XOF', code: 'XOF', symbol: 'Fr' },
  XAF: { name: 'CFA BEAC Francs - XAF', code: 'XAF', symbol: 'Fr' },
  CLP: { name: 'Chile Pesos - CLP', code: 'CLP', symbol: '$' },
  CNY: { name: 'China Yuan Renminbi - CNY', code: 'CNY', symbol: '¥' },
  COP: { name: 'Colombia Pesos - COP', code: 'COP', symbol: '$' },
  XPF: { name: 'CFP Francs - XPF', code: 'XPF', symbol: 'Fr' },
  CRC: { name: 'Costa Rica Colones - CRC', code: 'CRC', symbol: '₡' },
  HRK: { name: 'Croatia Kuna - HRK', code: 'HRK', symbol: 'kn' },
  CYP: { name: 'Cyprus Pounds - CYP', code: 'CYP', symbol: '£' },
  CZK: { name: 'Czech Republic Koruny - CZK', code: 'CZK', symbol: 'Kč' },
  DKK: { name: 'Denmark Kroner - DKK', code: 'DKK', symbol: 'kr' },
  DEM: { name: 'Deutsche (Germany) Marks - DEM', code: 'DEM', symbol: 'DM' },
  DOP: { name: 'Dominican Republic Pesos - DOP', code: 'DOP', symbol: 'RD$' },
  NLG: { name: 'Dutch (Netherlands) Guilders - NLG', code: 'NLG', symbol: 'ƒ' },
  XCD: { name: 'Eastern Caribbean Dollars - XCD', code: 'XCD', symbol: '$' },
  EGP: { name: 'Egypt Pounds - EGP', code: 'EGP', symbol: 'ج.م' },
  EEK: { name: 'Estonia Krooni - EEK', code: 'EEK', symbol: 'kr' },
  EUR: { name: 'Euro - EUR', code: 'EUR', symbol: '€' },
  FJD: { name: 'Fiji Dollars - FJD', code: 'FJD', symbol: '$' },
  FIM: { name: 'Finland Markkaa - FIM', code: 'FIM', symbol: 'mk' },
  FRF: { name: 'France Francs - FRF*', code: 'FRF*', symbol: 'Fr' },
  DEM: { name: 'Germany Deutsche Marks - DEM', code: 'DEM', symbol: 'DM' },
  XAU: { name: 'Gold Ounces - XAU', code: 'XAU', symbol: '' },
  GRD: { name: 'Greece Drachmae - GRD', code: 'GRD', symbol: 'Δρ' },
  GTQ: { name: 'Guatemalan Quetzal - GTQ', code: 'GTQ', symbol: 'Q' },
  NLG: {
    name: 'Holland (Netherlands) Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
  },
  HKD: { name: 'Hong Kong Dollars - HKD', code: 'HKD', symbol: 'HK$' },
  HUF: { name: 'Hungary Forint - HUF', code: 'HUF', symbol: 'Ft' },
  ISK: { name: 'Iceland Kronur - ISK', code: 'ISK', symbol: 'kr' },
  XDR: { name: 'IMF Special Drawing Right - XDR', code: 'XDR', symbol: '' },
  INR: { name: 'India Rupees - INR', code: 'INR', symbol: '₹' },
  IDR: { name: 'Indonesia Rupiahs - IDR', code: 'IDR', symbol: 'Rp' },
  IRR: { name: 'Iran Rials - IRR', code: 'IRR', symbol: 'ریال' },
  IQD: { name: 'Iraq Dinars - IQD', code: 'IQD', symbol: 'د.ع' },
  IEP: { name: 'Ireland Pounds - IEP*', code: 'IEP*', symbol: '£' },
  ILS: { name: 'Israel New Shekels - ILS', code: 'ILS', symbol: '₪' },
  ITL: { name: 'Italy Lire - ITL*', code: 'ITL*', symbol: '₤' },
  JMD: { name: 'Jamaica Dollars - JMD', code: 'JMD', symbol: 'J$' },
  JPY: { name: 'Japan Yen - JPY', code: 'JPY', symbol: '¥' },
  JOD: { name: 'Jordan Dinars - JOD', code: 'JOD', symbol: 'د.أ' },
  KES: { name: 'Kenya Shillings - KES', code: 'KES', symbol: 'KSh' },
  KRW: { name: 'Korea (South) Won - KRW', code: 'KRW', symbol: '₩' },
  KWD: { name: 'Kuwait Dinars - KWD', code: 'KWD', symbol: 'د.ك' },
  LBP: { name: 'Lebanon Pounds - LBP', code: 'LBP', symbol: 'ل.ل' },
  LUF: { name: 'Luxembourg Francs - LUF', code: 'LUF', symbol: 'Fr' },
  MYR: { name: 'Malaysia Ringgits - MYR', code: 'MYR', symbol: 'RM' },
  MTL: { name: 'Malta Liri - MTL', code: 'MTL', symbol: 'Lm' },
  MUR: { name: 'Mauritius Rupees - MUR', code: 'MUR', symbol: '₨' },
  MXN: { name: 'Mexico Pesos - MXN', code: 'MXN', symbol: '$' },
  MAD: { name: 'Morocco Dirhams - MAD', code: 'MAD', symbol: 'د.م.' },
  NLG: { name: 'Netherlands Guilders - NLG', code: 'NLG', symbol: 'ƒ' },
  NZD: { name: 'New Zealand Dollars - NZD', code: 'NZD', symbol: '$' },
  NOK: { name: 'Norway Kroner - NOK', code: 'NOK', symbol: 'kr' },
  OMR: { name: 'Oman Rials - OMR', code: 'OMR', symbol: 'ر.ع.' },
  PKR: { name: 'Pakistan Rupees - PKR', code: 'PKR', symbol: '₨' },
  XPD: { name: 'Palladium Ounces - XPD', code: 'XPD', symbol: '' },
  PEN: { name: 'Peru Nuevos Soles - PEN', code: 'PEN', symbol: 'S/' },
  PHP: { name: 'Philippines Pesos - PHP', code: 'PHP', symbol: '₱' },
  XPT: { name: 'Platinum Ounces - XPT', code: 'XPT', symbol: '' },
  PLN: { name: 'Poland Zlotych - PLN', code: 'PLN', symbol: 'zł' },
  PTE: { name: 'Portugal Escudos - PTE', code: 'PTE', symbol: '₡' },
  QAR: { name: 'Qatar Riyals - QAR', code: 'QAR', symbol: 'ر.ق' },
  RON: { name: 'Romania New Lei - RON', code: 'RON', symbol: 'lei' },
  ROL: { name: 'Romania Lei - ROL', code: 'ROL', symbol: 'lei' },
  RUB: { name: 'Russia Rubles - RUB', code: 'RUB', symbol: '₽' },
  SAR: { name: 'Saudi Arabia Riyals - SAR', code: 'SAR', symbol: 'ر.س' },
  XAG: { name: 'Silver Ounces - XAG', code: 'XAG', symbol: '' },
  SGD: { name: 'Singapore Dollars - SGD', code: 'SGD', symbol: 'S$' },
  SKK: { name: 'Slovakia Koruny - SKK', code: 'SKK', symbol: 'Sk' },
  SIT: { name: 'Slovenia Tolars - SIT', code: 'SIT', symbol: 'SIT' },
  ZAR: { name: 'South Africa Rand - ZAR', code: 'ZAR', symbol: 'R' },
  KRW: { name: 'South Korea Won - KRW', code: 'KRW', symbol: '₩' },
  ESP: { name: 'Spain Pesetas - ESP', code: 'ESP', symbol: '₧' },
  XDR: { name: 'Special Drawing Rights (IMF) - XDR', code: 'XDR', symbol: '' },
  LKR: { name: 'Sri Lanka Rupees - LKR', code: 'LKR', symbol: '₨' },
  SDD: { name: 'Sudan Dinars - SDD', code: 'SDD', symbol: 'د.س' },
  SEK: { name: 'Sweden Kronor - SEK', code: 'SEK', symbol: 'kr' },
  CHF: { name: 'Switzerland Francs - CHF', code: 'CHF', symbol: 'Fr' },
  TWD: { name: 'Taiwan New Dollars - TWD', code: 'TWD', symbol: 'NT$' },
  THB: { name: 'Thailand Baht - THB', code: 'THB', symbol: '฿' },
  TTD: {
    name: 'Trinidad and Tobago Dollars - TTD',
    code: 'TTD',
    symbol: 'TT$',
  },
  TND: { name: 'Tunisia Dinars - TND', code: 'TND', symbol: 'د.ت' },
  TRY: { name: 'Turkey New Lira - TRY', code: 'TRY', symbol: '₺' },
  AED: {
    name: 'United Arab Emirates Dirhams - AED',
    code: 'AED',
    symbol: 'د.إ',
  },
  GBP: { name: 'United Kingdom Pounds - GBP', code: 'GBP', symbol: '£' },
  USD: { name: 'United States Dollars - USD', code: 'USD', symbol: '$' },
  VEB: { name: 'Venezuela Bolivares - VEB', code: 'VEB', symbol: 'Bs' },
  VND: { name: 'Vietnam Dong - VND', code: 'VND', symbol: '₫' },
  ZMK: { name: 'Zambia Kwacha - ZMK', code: 'ZMK', symbol: 'ZK' },
};

const SEC_CURRENCIES = [
  {
    currency: 'America (United States) Dollars - USD',
    code: 'USD',
    symbol: '$',
  },
  { currency: 'Afghanistan Afghanis - AFN', code: 'AFN', symbol: '؋' },
  { currency: 'Albania Leke - ALL', code: 'ALL', symbol: 'Lek' },
  { currency: 'Algeria Dinars - DZD', code: 'DZD', symbol: 'د.ج' },
  { currency: 'Argentina Pesos - ARS', code: 'ARS', symbol: '$' },
  { currency: 'Australia Dollars - AUD', code: 'AUD', symbol: '$' },
  { currency: 'Austria Schillings - ATS', code: 'ATS', symbol: 'S' },
  { currency: 'Bahamas Dollars - BSD', code: 'BSD', symbol: '$' },
  { currency: 'Bahrain Dinars - BHD', code: 'BHD', symbol: '.د.ب' },
  { currency: 'Bangladesh Taka - BDT', code: 'BDT', symbol: '৳' },
  { currency: 'Barbados Dollars - BBD', code: 'BBD', symbol: '$' },
  { currency: 'Belgium Francs - BEF', code: 'BEF', symbol: 'fr.' },
  { currency: 'Bermuda Dollars - BMD', code: 'BMD', symbol: '$' },
  { currency: 'Brazil Reais - BRL', code: 'BRL', symbol: 'R$' },
  { currency: 'Bulgaria Leva - BGN', code: 'BGN', symbol: 'лв' },
  { currency: 'Canada Dollars - CAD', code: 'CAD', symbol: '$' },
  { currency: 'CFA BCEAO Francs - XOF', code: 'XOF', symbol: 'Fr' },
  { currency: 'CFA BEAC Francs - XAF', code: 'XAF', symbol: 'Fr' },
  { currency: 'Chile Pesos - CLP', code: 'CLP', symbol: '$' },
  { currency: 'China Yuan Renminbi - CNY', code: 'CNY', symbol: '¥' },
  { currency: 'RMB (China Yuan Renminbi) - CNY', code: 'CNY', symbol: '¥' },
  { currency: 'Colombia Pesos - COP', code: 'COP', symbol: '$' },
  { currency: 'CFP Francs - XPF', code: 'XPF', symbol: 'Fr' },
  { currency: 'Costa Rica Colones - CRC', code: 'CRC', symbol: '₡' },
  { currency: 'Croatia Kuna - HRK', code: 'HRK', symbol: 'kn' },
  { currency: 'Cyprus Pounds - CYP', code: 'CYP', symbol: '£' },
  { currency: 'Czech Republic Koruny - CZK', code: 'CZK', symbol: 'Kč' },
  { currency: 'Denmark Kroner - DKK', code: 'DKK', symbol: 'kr' },
  { currency: 'Deutsche (Germany) Marks - DEM', code: 'DEM', symbol: 'DM' },
  { currency: 'Dominican Republic Pesos - DOP', code: 'DOP', symbol: 'RD$' },
  { currency: 'Dutch (Netherlands) Guilders - NLG', code: 'NLG', symbol: 'ƒ' },
  { currency: 'Eastern Caribbean Dollars - XCD', code: 'XCD', symbol: '$' },
  { currency: 'Egypt Pounds - EGP', code: 'EGP', symbol: 'ج.م' },
  { currency: 'Estonia Krooni - EEK', code: 'EEK', symbol: 'kr' },
  { currency: 'Euro - EUR', code: 'EUR', symbol: '€' },
  { currency: 'Fiji Dollars - FJD', code: 'FJD', symbol: '$' },
  { currency: 'Finland Markkaa - FIM', code: 'FIM', symbol: 'mk' },
  { currency: 'France Francs - FRF*', code: 'FRF*', symbol: 'Fr' },
  { currency: 'Germany Deutsche Marks - DEM', code: 'DEM', symbol: 'DM' },
  { currency: 'Gold Ounces - XAU', code: 'XAU', symbol: '' },
  { currency: 'Greece Drachmae - GRD', code: 'GRD', symbol: 'Δρ' },
  { currency: 'Guatemalan Quetzal - GTQ', code: 'GTQ', symbol: 'Q' },
  {
    currency: 'Holland (Netherlands) Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
  },
  { currency: 'Hong Kong Dollars - HKD', code: 'HKD', symbol: 'HK$' },
  { currency: 'Hungary Forint - HUF', code: 'HUF', symbol: 'Ft' },
  { currency: 'Iceland Kronur - ISK', code: 'ISK', symbol: 'kr' },
  { currency: 'IMF Special Drawing Right - XDR', code: 'XDR', symbol: '' },
  { currency: 'India Rupees - INR', code: 'INR', symbol: '₹' },
  { currency: 'Indonesia Rupiahs - IDR', code: 'IDR', symbol: 'Rp' },
  { currency: 'Iran Rials - IRR', code: 'IRR', symbol: 'ریال' },
  { currency: 'Iraq Dinars - IQD', code: 'IQD', symbol: 'د.ع' },
  { currency: 'Ireland Pounds - IEP*', code: 'IEP*', symbol: '£' },
  { currency: 'Israel New Shekels - ILS', code: 'ILS', symbol: '₪' },
  { currency: 'Italy Lire - ITL*', code: 'ITL*', symbol: '₤' },
  { currency: 'Jamaica Dollars - JMD', code: 'JMD', symbol: 'J$' },
  { currency: 'Japan Yen - JPY', code: 'JPY', symbol: '¥' },
  { currency: 'Jordan Dinars - JOD', code: 'JOD', symbol: 'د.أ' },
  { currency: 'Kenya Shillings - KES', code: 'KES', symbol: 'KSh' },
  { currency: 'Korea (South) Won - KRW', code: 'KRW', symbol: '₩' },
  { currency: 'Kuwait Dinars - KWD', code: 'KWD', symbol: 'د.ك' },
  { currency: 'Lebanon Pounds - LBP', code: 'LBP', symbol: 'ل.ل' },
  { currency: 'Luxembourg Francs - LUF', code: 'LUF', symbol: 'Fr' },
  { currency: 'Malaysia Ringgits - MYR', code: 'MYR', symbol: 'RM' },
  { currency: 'Malta Liri - MTL', code: 'MTL', symbol: 'Lm' },
  { currency: 'Mauritius Rupees - MUR', code: 'MUR', symbol: '₨' },
  { currency: 'Mexico Pesos - MXN', code: 'MXN', symbol: '$' },
  { currency: 'Morocco Dirhams - MAD', code: 'MAD', symbol: 'د.م.' },
  { currency: 'Netherlands Guilders - NLG', code: 'NLG', symbol: 'ƒ' },

  { currency: 'New Zealand Dollars - NZD', code: 'NZD', symbol: '$' },

  { currency: 'Norway Kroner - NOK', code: 'NOK', symbol: 'kr' },

  { currency: 'Oman Rials - OMR', code: 'OMR', symbol: 'ر.ع.' },

  { currency: 'Pakistan Rupees - PKR', code: 'PKR', symbol: '₨' },

  { currency: 'Palladium Ounces - XPD', code: 'XPD', symbol: '' },

  { currency: 'Peru Nuevos Soles - PEN', code: 'PEN', symbol: 'S/' },

  { currency: 'Philippines Pesos - PHP', code: 'PHP', symbol: '₱' },

  { currency: 'Platinum Ounces - XPT', code: 'XPT', symbol: '' },

  { currency: 'Poland Zlotych - PLN', code: 'PLN', symbol: 'zł' },
  { currency: 'Portugal Escudos - PTE', code: 'PTE', symbol: '₡' },
  { currency: 'Qatar Riyals - QAR', code: 'QAR', symbol: 'ر.ق' },
  { currency: 'Romania New Lei - RON', code: 'RON', symbol: 'lei' },
  { currency: 'Romania Lei - ROL', code: 'ROL', symbol: 'lei' },
  { currency: 'Russia Rubles - RUB', code: 'RUB', symbol: '₽' },
  { currency: 'Saudi Arabia Riyals - SAR', code: 'SAR', symbol: 'ر.س' },
  { currency: 'Silver Ounces - XAG', code: 'XAG', symbol: '' },
  { currency: 'Singapore Dollars - SGD', code: 'SGD', symbol: 'S$' },
  { currency: 'Slovakia Koruny - SKK', code: 'SKK', symbol: 'Sk' },
  { currency: 'Slovenia Tolars - SIT', code: 'SIT', symbol: 'SIT' },
  { currency: 'South Africa Rand - ZAR', code: 'ZAR', symbol: 'R' },
  { currency: 'South Korea Won - KRW', code: 'KRW', symbol: '₩' },
  { currency: 'Spain Pesetas - ESP', code: 'ESP', symbol: '₧' },
  { currency: 'Special Drawing Rights (IMF) - XDR', code: 'XDR', symbol: '' },
  { currency: 'Sri Lanka Rupees - LKR', code: 'LKR', symbol: '₨' },
  { currency: 'Sudan Dinars - SDD', code: 'SDD', symbol: 'د.س' },
  { currency: 'Sweden Kronor - SEK', code: 'SEK', symbol: 'kr' },
  { currency: 'Switzerland Francs - CHF', code: 'CHF', symbol: 'Fr' },
  { currency: 'Taiwan New Dollars - TWD', code: 'TWD', symbol: 'NT$' },
  { currency: 'Thailand Baht - THB', code: 'THB', symbol: '฿' },
  { currency: 'Trinidad and Tobago Dollars - TTD', code: 'TTD', symbol: 'TT$' },
  { currency: 'Tunisia Dinars - TND', code: 'TND', symbol: 'د.ت' },
  { currency: 'Turkey New Lira - TRY', code: 'TRY', symbol: '₺' },
  {
    currency: 'United Arab Emirates Dirhams - AED',
    code: 'AED',
    symbol: 'د.إ',
  },
  { currency: 'United Kingdom Pounds - GBP', code: 'GBP', symbol: '£' },
  { currency: 'United States Dollars - USD', code: 'USD', symbol: '$' },
  { currency: 'Venezuela Bolivares - VEB', code: 'VEB', symbol: 'Bs' },
  { currency: 'Vietnam Dong - VND', code: 'VND', symbol: '₫' },
  { currency: 'Zambia Kwacha - ZMK', code: 'ZMK', symbol: 'ZK' },
];

const NEW_SEC_CURRENCIES = [
  {
    currency: 'America (United States) Dollars - USD',
    code: 'USD',
    symbol: '$',
    countryCode: 'US',
  },
  {
    currency: 'Afghanistan Afghanis - AFN',
    code: 'AFN',
    symbol: '؋',
    countryCode: 'AF',
  },
  {
    currency: 'Albania Leke - ALL',
    code: 'ALL',
    symbol: 'Lek',
    countryCode: 'AL',
  },
  {
    currency: 'Algeria Dinars - DZD',
    code: 'DZD',
    symbol: 'د.ج',
    countryCode: 'DZ',
  },
  {
    currency: 'Argentina Pesos - ARS',
    code: 'ARS',
    symbol: '$',
    countryCode: 'AR',
  },
  {
    currency: 'Australia Dollars - AUD',
    code: 'AUD',
    symbol: '$',
    countryCode: 'AU',
  },
  {
    currency: 'Austria Schillings - ATS',
    code: 'ATS',
    symbol: 'S',
    countryCode: 'AT',
  },
  {
    currency: 'Bahamas Dollars - BSD',
    code: 'BSD',
    symbol: '$',
    countryCode: 'BS',
  },
  {
    currency: 'Bahrain Dinars - BHD',
    code: 'BHD',
    symbol: '.د.ب',
    countryCode: 'BH',
  },
  {
    currency: 'Bangladesh Taka - BDT',
    code: 'BDT',
    symbol: '৳',
    countryCode: 'BD',
  },
  {
    currency: 'Barbados Dollars - BBD',
    code: 'BBD',
    symbol: '$',
    countryCode: 'BB',
  },
  {
    currency: 'Belgium Francs - BEF',
    code: 'BEF',
    symbol: 'fr.',
    countryCode: 'BE',
  },
  {
    currency: 'Bermuda Dollars - BMD',
    code: 'BMD',
    symbol: '$',
    countryCode: 'BM',
  },
  {
    currency: 'Brazil Reais - BRL',
    code: 'BRL',
    symbol: 'R$',
    countryCode: 'BR',
  },
  {
    currency: 'Bulgaria Leva - BGN',
    code: 'BGN',
    symbol: 'лв',
    countryCode: 'BG',
  },
  {
    currency: 'Canada Dollars - CAD',
    code: 'CAD',
    symbol: '$',
    countryCode: 'CA',
  },
  {
    currency: 'CFA BCEAO Francs - XOF',
    code: 'XOF',
    symbol: 'Fr',
    countryCode: 'CI',
  },
  {
    currency: 'CFA BEAC Francs - XAF',
    code: 'XAF',
    symbol: 'Fr',
    countryCode: 'CM',
  },
  {
    currency: 'Chile Pesos - CLP',
    code: 'CLP',
    symbol: '$',
    countryCode: 'CL',
  },
  {
    currency: 'China Yuan Renminbi - CNY',
    code: 'CNY',
    symbol: '¥',
    countryCode: 'CN',
  },
  {
    currency: 'RMB (China Yuan Renminbi) - CNY',
    code: 'CNY',
    symbol: '¥',
    countryCode: 'CN',
  },
  {
    currency: 'Colombia Pesos - COP',
    code: 'COP',
    symbol: '$',
    countryCode: 'CO',
  },
  {
    currency: 'CFP Francs - XPF',
    code: 'XPF',
    symbol: 'Fr',
    countryCode: 'PF',
  },
  {
    currency: 'Costa Rica Colones - CRC',
    code: 'CRC',
    symbol: '₡',
    countryCode: 'CR',
  },
  {
    currency: 'Croatia Kuna - HRK',
    code: 'HRK',
    symbol: 'kn',
    countryCode: 'HR',
  },
  {
    currency: 'Cyprus Pounds - CYP',
    code: 'CYP',
    symbol: '£',
    countryCode: 'CY',
  },
  {
    currency: 'Czech Republic Koruny - CZK',
    code: 'CZK',
    symbol: 'Kč',
    countryCode: 'CZ',
  },
  {
    currency: 'Denmark Kroner - DKK',
    code: 'DKK',
    symbol: 'kr',
    countryCode: 'DK',
  },
  {
    currency: 'Deutsche (Germany) Marks - DEM',
    code: 'DEM',
    symbol: 'DM',
    countryCode: 'DE',
  },
  {
    currency: 'Dominican Republic Pesos - DOP',
    code: 'DOP',
    symbol: 'RD$',
    countryCode: 'DO',
  },
  {
    currency: 'Dutch (Netherlands) Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
    countryCode: 'NL',
  },
  {
    currency: 'Eastern Caribbean Dollars - XCD',
    code: 'XCD',
    symbol: '$',
    countryCode: 'VC',
  },
  {
    currency: 'Egypt Pounds - EGP',
    code: 'EGP',
    symbol: 'ج.م',
    countryCode: 'EG',
  },
  {
    currency: 'Estonia Krooni - EEK',
    code: 'EEK',
    symbol: 'kr',
    countryCode: 'EE',
  },
  { currency: 'Euro - EUR', code: 'EUR', symbol: '€', countryCode: 'EU' },
  {
    currency: 'Fiji Dollars - FJD',
    code: 'FJD',
    symbol: '$',
    countryCode: 'FJ',
  },
  {
    currency: 'Finland Markkaa - FIM',
    code: 'FIM',
    symbol: 'mk',
    countryCode: 'FI',
  },
  {
    currency: 'France Francs - FRF*',
    code: 'FRF*',
    symbol: 'Fr',
    countryCode: 'FR',
  },
  {
    currency: 'Germany Deutsche Marks - DEM',
    code: 'DEM',
    symbol: 'DM',
    countryCode: 'DE',
  },
  { currency: 'Gold Ounces - XAU', code: 'XAU', symbol: '', countryCode: '' },
  {
    currency: 'Greece Drachmae - GRD',
    code: 'GRD',
    symbol: 'Δρ',
    countryCode: 'GR',
  },
  {
    currency: 'Guatemalan Quetzal - GTQ',
    code: 'GTQ',
    symbol: 'Q',
    countryCode: 'GT',
  },
  {
    currency: 'Holland (Netherlands) Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
    countryCode: 'NL',
  },
  {
    currency: 'Hong Kong Dollars - HKD',
    code: 'HKD',
    symbol: 'HK$',
    countryCode: 'HK',
  },
  {
    currency: 'Hungary Forint - HUF',
    code: 'HUF',
    symbol: 'Ft',
    countryCode: 'HU',
  },
  {
    currency: 'Iceland Kronur - ISK',
    code: 'ISK',
    symbol: 'kr',
    countryCode: 'IS',
  },
  {
    currency: 'IMF Special Drawing Right - XDR',
    code: 'XDR',
    symbol: '',
    countryCode: 'XM',
  },
  {
    currency: 'India Rupees - INR',
    code: 'INR',
    symbol: '₹',
    countryCode: 'IN',
  },
  {
    currency: 'Indonesia Rupiahs - IDR',
    code: 'IDR',
    symbol: 'Rp',
    countryCode: 'ID',
  },
  {
    currency: 'Iran Rials - IRR',
    code: 'IRR',
    symbol: 'ریال',
    countryCode: 'IR',
  },
  {
    currency: 'Iraq Dinars - IQD',
    code: 'IQD',
    symbol: 'د.ع',
    countryCode: 'IQ',
  },
  {
    currency: 'Ireland Pounds - IEP*',
    code: 'IEP*',
    symbol: '£',
    countryCode: 'IE',
  },
  {
    currency: 'Israel New Shekels - ILS',
    code: 'ILS',
    symbol: '₪',
    countryCode: 'IL',
  },
  {
    currency: 'Italy Lire - ITL*',
    code: 'ITL*',
    symbol: '₤',
    countryCode: 'IT',
  },
  {
    currency: 'Jamaica Dollars - JMD',
    code: 'JMD',
    symbol: 'J$',
    countryCode: 'JM',
  },
  { currency: 'Japan Yen - JPY', code: 'JPY', symbol: '¥', countryCode: 'JP' },
  {
    currency: 'Jordan Dinars - JOD',
    code: 'JOD',
    symbol: 'د.أ',
    countryCode: 'JO',
  },
  {
    currency: 'Kenya Shillings - KES',
    code: 'KES',
    symbol: 'KSh',
    countryCode: 'KE',
  },
  {
    currency: 'Korea (South) Won - KRW',
    code: 'KRW',
    symbol: '₩',
    countryCode: 'KR',
  },
  {
    currency: 'Kuwait Dinars - KWD',
    code: 'KWD',
    symbol: 'د.ك',
    countryCode: 'KW',
  },
  {
    currency: 'Lebanon Pounds - LBP',
    code: 'LBP',
    symbol: 'ل.ل',
    countryCode: 'LB',
  },
  {
    currency: 'Luxembourg Francs - LUF',
    code: 'LUF',
    symbol: 'Fr',
    countryCode: 'LU',
  },
  {
    currency: 'Malaysia Ringgits - MYR',
    code: 'MYR',
    symbol: 'RM',
    countryCode: 'MY',
  },
  {
    currency: 'Malta Liri - MTL',
    code: 'MTL',
    symbol: 'Lm',
    countryCode: 'MT',
  },
  {
    currency: 'Mauritius Rupees - MUR',
    code: 'MUR',
    symbol: '₨',
    countryCode: 'MU',
  },
  {
    currency: 'Mexico Pesos - MXN',
    code: 'MXN',
    symbol: '$',
    countryCode: 'MX',
  },
  {
    currency: 'Morocco Dirhams - MAD',
    code: 'MAD',
    symbol: 'د.م.',
    countryCode: 'MA',
  },
  {
    currency: 'Netherlands Guilders - NLG',
    code: 'NLG',
    symbol: 'ƒ',
    countryCode: 'NL',
  },
  {
    currency: 'New Zealand Dollars - NZD',
    code: 'NZD',
    symbol: '$',
    countryCode: 'NZ',
  },
  {
    currency: 'Norway Kroner - NOK',
    code: 'NOK',
    symbol: 'kr',
    countryCode: 'NO',
  },
  {
    currency: 'Oman Rials - OMR',
    code: 'OMR',
    symbol: 'ر.ع.',
    countryCode: 'OM',
  },
  {
    currency: 'Pakistan Rupees - PKR',
    code: 'PKR',
    symbol: '₨',
    countryCode: 'PK',
  },
  {
    currency: 'Palladium Ounces - XPD',
    code: 'XPD',
    symbol: '',
    countryCode: '',
  },
  {
    currency: 'Peru Nuevos Soles - PEN',
    code: 'PEN',
    symbol: 'S/',
    countryCode: 'PE',
  },
  {
    currency: 'Philippines Pesos - PHP',
    code: 'PHP',
    symbol: '₱',
    countryCode: 'PH',
  },
  {
    currency: 'Platinum Ounces - XPT',
    code: 'XPT',
    symbol: '',
    countryCode: '',
  },
  {
    currency: 'Poland Zlotych - PLN',
    code: 'PLN',
    symbol: 'zł',
    countryCode: 'PL',
  },
  {
    currency: 'Portugal Escudos - PTE',
    code: 'PTE',
    symbol: '₡',
    countryCode: 'PT',
  },
  {
    currency: 'Qatar Riyals - QAR',
    code: 'QAR',
    symbol: 'ر.ق',
    countryCode: 'QA',
  },
  {
    currency: 'Romania New Lei - RON',
    code: 'RON',
    symbol: 'lei',
    countryCode: 'RO',
  },
  {
    currency: 'Romania Lei - ROL',
    code: 'ROL',
    symbol: 'lei',
    countryCode: 'RO',
  },
  {
    currency: 'Russia Rubles - RUB',
    code: 'RUB',
    symbol: '₽',
    countryCode: 'RU',
  },
  {
    currency: 'Saudi Arabia Riyals - SAR',
    code: 'SAR',
    symbol: 'ر.س',
    countryCode: 'SA',
  },
  { currency: 'Silver Ounces - XAG', code: 'XAG', symbol: '', countryCode: '' },
  {
    currency: 'Singapore Dollars - SGD',
    code: 'SGD',
    symbol: 'S$',
    countryCode: 'SG',
  },
  {
    currency: 'Slovakia Koruny - SKK',
    code: 'SKK',
    symbol: 'Sk',
    countryCode: 'SK',
  },
  {
    currency: 'Slovenia Tolars - SIT',
    code: 'SIT',
    symbol: 'SIT',
    countryCode: 'SI',
  },
  {
    currency: 'South Africa Rand - ZAR',
    code: 'ZAR',
    symbol: 'R',
    countryCode: 'ZA',
  },
  {
    currency: 'South Korea Won - KRW',
    code: 'KRW',
    symbol: '₩',
    countryCode: 'KR',
  },
  {
    currency: 'Spain Pesetas - ESP',
    code: 'ESP',
    symbol: '₧',
    countryCode: 'ES',
  },
  {
    currency: 'Special Drawing Rights (IMF) - XDR',
    code: 'XDR',
    symbol: '',
    countryCode: 'XM',
  },
  {
    currency: 'Sri Lanka Rupees - LKR',
    code: 'LKR',
    symbol: '₨',
    countryCode: 'LK',
  },
  {
    currency: 'Sudan Dinars - SDD',
    code: 'SDD',
    symbol: 'د.س',
    countryCode: 'SD',
  },
  {
    currency: 'Sweden Kronor - SEK',
    code: 'SEK',
    symbol: 'kr',
    countryCode: 'SE',
  },
  {
    currency: 'Switzerland Francs - CHF',
    code: 'CHF',
    symbol: 'Fr',
    countryCode: 'CH',
  },
  {
    currency: 'Taiwan New Dollars - TWD',
    code: 'TWD',
    symbol: 'NT$',
    countryCode: 'TW',
  },
  {
    currency: 'Thailand Baht - THB',
    code: 'THB',
    symbol: '฿',
    countryCode: 'TH',
  },
  {
    currency: 'Trinidad and Tobago Dollars - TTD',
    code: 'TTD',
    symbol: 'TT$',
    countryCode: 'TT',
  },
  {
    currency: 'Tunisia Dinars - TND',
    code: 'TND',
    symbol: 'د.ت',
    countryCode: 'TN',
  },
  {
    currency: 'Turkey New Lira - TRY',
    code: 'TRY',
    symbol: '₺',
    countryCode: 'TR',
  },
  {
    currency: 'United Arab Emirates Dirhams - AED',
    code: 'AED',
    symbol: 'د.إ',
    countryCode: 'AE',
  },
  {
    currency: 'United Kingdom Pounds - GBP',
    code: 'GBP',
    symbol: '£',
    countryCode: 'GB',
  },
  {
    currency: 'United States Dollars - USD',
    code: 'USD',
    symbol: '$',
    countryCode: 'US',
  },
  {
    currency: 'Venezuela Bolivares - VEB',
    code: 'VEB',
    symbol: 'Bs',
    countryCode: 'VE',
  },
  {
    currency: 'Vietnam Dong - VND',
    code: 'VND',
    symbol: '₫',
    countryCode: 'VN',
  },
  {
    currency: 'Zambia Kwacha - ZMK',
    code: 'ZMK',
    symbol: 'ZK',
    countryCode: 'ZM',
  },
];

const SEC_DEFAULT_CURRENCY = {
  currency: 'United Kingdom Pounds - GBP',
  code: 'GBP',
  symbol: '£',
};

const SEC_DSS_DEFAULT_CURRENCY = {
  currency: 'America (United States) Dollars - USD',
  code: 'USD',
  symbol: '$',
};

const INITIATE_ORDER_TYPE = {
  paper: 'Assignment/Project',
  meeting: 'Online Meeting',
};

const APP_NAMES = {
  HYBRID_RESEARCH_CENTER: 'Hybrid Reseach Center',
  EMIRATES_RESEARCH_CENTER: 'Emirates Research Center',
  DIGITAL_SKY_SERVICES: 'Digital Sky Services',
  BRAIN_BENCH: 'Brain Bench',
};

const UserRole = {
  client: 'client',
  agent: 'agent',
  agentsClient: 'agentsClient',
};

const PAYMENT_OPTIONS = {
  FULL_PAYMENT: 'FULL_PAYMENT',
  PARTIAL_PAYMENT: 'PARTIAL_PAYMENT',
};

const MEEZAN_PAYMENT_SUCCESS_TITLE = 'Receipt';
const MEEZAN_PAYMENT_SUCCESS_TITLE_2 = 'Order Success';

const ORDER_STATUS = {
  REVISION: 'Revision',
  CLOSED: 'close',
  WORKING: 'working',
};

const TRANSACTION_HISTORY_TYPES={
  WALLET:'wallet',
  ORDER:'order',
  TIP:'tip',
}

export {
  ALL_CURRENCIES_OBJ,
  APP_NAMES,
  APP_NAME_CODES,
  INITIATE_ORDER_TYPE,
  NEW_SEC_CURRENCIES,
  SEC_CURRENCIES,
  SEC_DEFAULT_CURRENCY,
  UserRole,
  PAYMENT_OPTIONS,
  MEEZAN_PAYMENT_SUCCESS_TITLE,
  MEEZAN_PAYMENT_SUCCESS_TITLE_2,
  ORDER_STATUS,
  TRANSACTION_HISTORY_TYPES,
  SEC_DSS_DEFAULT_CURRENCY
};
